# Danksagung {-}
Diese Arbeit kam nur dank der freundlichen Unterstützung ausgewiesener Amphibienexpert*innen zustande. Vielen Dank an Petra Ramseier und Benedikt Schmidt. Die Daten wurden von der kantonalen Naturschutzfachstelle zur Verfügung gestellt. Ein besonderen Dank dafür geht an Markus Plattner.
Ebenfalls ein grosses Dankeschön gebührt Professorin Gudrun Wallentin für ihre Unterstützung.


# Zusammenfassung {-}
In der Gemeinde Allschwil wurden von einigen Jahren Italienische Kammmolche gefunden. Diese Art ist südlich der Alpen beheimatet. In den wenigen Standorten, wo die Italienischen Kammmolche nördlich der Alpen eingeschleppt wurden, führte das zur Verdrängung des Nördlichen Kammmolches, einer gefährdeten Rote-Liste-Art. Um die negativen Auswirkungen der standortfremden Art zu begrenzen, wurde ein Bekämpfungsprogramm gestartet. Das vorliegende Modell dient der Untersuchung der Populationsdynamik dieser Kammmolche und soll die Wirksamkeit der Bekämpfungsmethoden überprüfen. Das Modell, sein Aufbau und seine Funktionsweise sind in dieser Arbeit anhand des ODD- Protokolls beschrieben, zudem ist das Modell auf dem Github-repository [phfranke/masterarbeit](https://github.com/phfranke/masterarbeit) verfügbar. Das agentenbasierte Modell wurde mit der Software GAMA erstellt und bildet die Entwicklungsstadien der Kammmolche nach. Dabei wird für die immobilen Stadien (Eier und Larven) eine formelbasierte Modellierung angewendet und für die späteren Stadien (Juvenile und Adulte) die agentenbasierte Modellierung. Diese Stadien unternehmen Wanderungen, welche es ihnen ermöglicht, neue Gewässer zu besiedeln. Damit kann die Entwicklung der Population beobeachtet werden, sowohl was die räumliche Verbreitung als auch die zahlenmässige Präsenz betrifft. Ab dem Jahr 2021 sind Bekämpfungsmassnahmen implementiert.
Um das Modell mit den realen Verhältnissen abzugleichen, wurden Experimente zur Kalibrierung und zur Validierung des Modells entwickelt und durchgeführt. Dazu dienten die Fangzahlen aus der Bekämpfungskampagne der Jahre 2021 und 2022. Leider konnte die Validierung nicht positiv abgeschlossen werden. Es zeigte sich, dass starke, jährliche Schwankungen die Resultate beeinträchtigen. Die Validität des konzeptionellen Modells wurde durch Experten bestätigt, weshalb die Resultate eine gewisse Aussagekraft behalten. Die Quelle der Oszillationen kann in dieser Arbeit auf einen Prozess zurückgeführt werden, welcher durch eine zeitverzögerte Rückkoppelung möglicherweise einen Bull Whip Effect auslöst.
Die Resultate zeigen, dass die Kammmolche nur in einer von insgesamt sechs Modellvarianten komplett ausgerottet werden konnten. In dieser Variante werden die Bekämpfungsmassnahmen auf sämtliche Gewässer ausgeweitet und die Effizienz der Massnahmen beträgt `95%`. Das bedeutet, dass sich weniger als `5%` der Kammmolche den Bekämpfungsmassnahmen entziehen können und trotz der Massnahmen eine Fortpflanzungsmöglichkeit finden.  Daraus kann geschlussfolgert werden, dass die Bekämpfung von Kammmolchen nur möglich ist, wenn die Besiedelung neuer Gewässer entdeckt und die Bekämpfung der Kammmolche auch auf diese Gewässer ausgedehnt wird. Zudem lässt das Modell vermuten, dass die Bekämpfungskampagne wohl bis gegen 2030 durchgeführt werden muss.


# Abstract {-}
A few years ago some individuals of the invasive Italien Crested Newts were found in Allschwil near Basel. Several Studies across Europe show, that Italian Crested Newts on the northern side of the alps are a threat to the protected species Northern Crested Newts. The Northern Crested Newts are endangered and local conservation measures has also the goal to protect and enhance this populations. To protect the local population of the Northern Crested Newts, control measures have been developed which should lead to the local extinction of the Italian Crested Newt.
This Masterthesis develops an agent-based model to examine the population dynamics of the Italian Crested Newt in Allschwil and also implements the control measures. Since its not possible to measure the effectiveness of the control measures, this model aims to predict whether the measures will be successful and how many years the measures have to be installed. The model uses the GAMA- Platform and follows an agent-based method. The model can be found on the Github-repository [phfranke/masterarbeit](https://github.com/phfranke/masterarbeit). This documentation follows the ODD-protocol.
The model reproduces the life cycle of the newts. All life stages are implemented. The early stages (egg and larva) are immobile and are modeled following an equation based paradigm. The stages juvenile and adult follow the agent based paradigm. Thereby the modeled newts are enabled to migrate and colonize new ponds. The model is capable to show the development of the population of the Italian Crested Newts in both number and colonized area.
To adapt the model as near as possible to the reality, the model was calibrated through several experiments. The data for the calibration originate from the control measures, which are implemented since 2021. The data of the year 2021 are used for calibration, the data from 2022 are taken to validate the model.
Unfortunately the validation ends not positive. Due to strong oscillation, the results show inexplicable divergences from year to year which leads in failing validation. The source of the oscillation can be traced back to a process which implements a time delay and presumably causes a Bull Whip Effect. As experts confirm the conceptual model as reliable, the results keep a certain significance.
From overall 6 model versions only one version leads to extinction of the Italian Crested Newts. In this version, the control measures are expanded not only in a few ponds but in all ponds in the region. Further the individual newts have only `5%` probability to escape the control measures and reproduce despite the control fences. So can be shown, that for the extinction of the invasive newts, the control measures have to be very effective and have to cover all the colonized ponds. Also with effective and seamless combat, the measures have to be kept upright until the newts are extinct. The model predict, that this can last until 2030.

