Parameter <- c(
  'number_newt_start',
  'starting_date',
  'stop_date',
  'step',
  'calibrationEnd',
  'survival_egg',
  'survival_larva',
  'survival_juvenil',
  'survival_adult',
  'density_koeff',
  'density_off',
  'maxAge_egg',
  'maxAge_larva',
  'maxAge_juv',
  'clutchSize',
  'reproductionBreak',
  'migrationRate_adult',
  'migrationRate_juv',
  'migration_velocity _adult',
  'migration_velocity _juv',
  'migration_time',
  'start_catching',
  'probalityCatch',
  'catching_allPonds'
)
Bezeichnung <- c(
  'Anzahl Adulte zu Beginn',
  'Start Datum',
  'End Datum',
  'Zeitschritt',
  'End Datum Kalibration',
  '&Uuml;berlebensrate Eier',
  '&Uuml;berlebensrate Larven',
  '&Uuml;berlebensrate Juvenile',
  'j&auml;hrl. &Uuml;berlebensrate Adulte',
  'Abh&auml;ngigkeit Larvendichte/Sterblichkeit',
  'Dichteabhängigkeit abschalten',
  'Entwicklungsdauer Ei',
  'Entwicklungsdauer Larve',
  'Entwicklungsdauer Juvenil',
  'Gelegegr&ouml;sse',
  'Fortpflanzungspause',
  'Rate der Wanderer Adult',
  'Rate der Wanderer Juvenil',
  'Wandergeschwindigkeit Adult',
  'Wandergeschwindigkeit Juvenil',
  'Dauer Wanderung',
  'Startjahr Bek&auml;mpfung',
  'Wahrscheinlichkeit gefangen zu werden',
  'Bekämpfung in allen Gewässern'
)
Einheit <- c(
  'Stk.',
  'Datum',
  'Datum',
  'Tag',
  'Datum',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  'Tage',
  'Tage',
  'Tage',
  'Eier',
  'Jahr',
  '-',
  '-',
  'm/Tag',
  'm/Tag',
  'Tage',
  'Jahr',
  '-',
  '-'
)
Wert <- c(
  '50',
  '1.1.2000',
  '31.12.2049',
  '1',
  '1.1.2022',
  '0.5',
  '0.4',
  '0.4',
  '0.5',
  '0.008',
  'FALSE',
  '15',
  '90',
  '200',
  '300',
  '2',
  '0.12',
  '0.373',
  '10',
  '15',
  '13',
  '2021',
  '0.8',
  'TRUE'
)
Herkunft <- c(
  'Annahme',
  'Annahme',
  'Annahme',
  'Annahme',
  'Annahme',
  '@horner1985normal',
  'Annahme',
  'Annahme',
  '@jehle2011crested',
  'Kalibration',
  'Annahme',
  'Annahme',
  '@meyer2009schlangenspuren',
  '@meyer2009schlangenspuren',
  '@jehle2011crested',
  '@meyer2009schlangenspuren',
  '@kupfer2000population',
  '@kupfer2000population',
  'Annahme',
  'Annahme',
  'Kalibration',
  'Mündliche Information Experten',
  'Annahme',
  'Annahme'
)
tab_parameter <- cbind(Parameter,Bezeichnung,Einheit,Wert,Herkunft)
