Parameter <- c(
  'number_newt_start',
  'starting_date',
  'stop_date',
  'step',
  'calibrationEnd',
  'survival_egg',
  'survival_larva',
  'survival_juvenil',
  'survival_adult',
  'density_koeff',
  'maxAge_egg',
  'maxAge_larva',
  'maxAge_juv',
  'clutchSize',
  'reproductionBreak',
  'migrationRate_adult',
  'migrationRate_juv',
  'migration_time',
  'start_catching',
  'probalityCatch'
)
Bezeichnung <- c(
  'Anzahl Kammmolche zu Beginn',
  'Start Datum',
  'End Datum',
  'Zeitschritt',
  'End Datum Kalibration',
  '&Uuml;berlebensrate Eier',
  '&Uuml;berlebensrate Larven',
  '&Uuml;berlebensrate Juvenile',
  '&Uuml;berlebensrate Adulte, j&auml;hrlich',
  'Abh&auml;ngigkeit Larvendichte/Sterblichkeit',
  'Entwicklungsdauer Ei',
  'Entwicklungsdauer Larve',
  'Entwicklungsdauer Juvenil',
  'Gelegegr&ouml;sse',
  'Fortpflanzungspause',
  'Rate der Wanderer Adult',
  'Rate der Wanderer Juvenil',
  'Dauer Wanderung',
  'Startjahr Bek&auml;mpfung',
  'Wahrscheinlichkeit gefangen zu werden'
)
Einheit <- c(
  'Stk.',
  'Datum',
  'Datum',
  'Tag',
  'Datum',
  '-',
  '-',
  '-',
  '-',
  '-',
  'Tage',
  'Tage',
  'Tage',
  'Eier/Weibchen',
  'Jahr',
  '-',
  '-',
  'Tage',
  'Jahr',
  '-'
)
Wert <- c(
  '50',
  '1.1.2000',
  '31.12.2049',
  '1',
  '1.1.2022',
  '0.5',
  '0.4',
  '0.4',
  '0.5',
  '0.01',
  '15',
  '90',
  '200',
  '300',
  '2',
  '0.12',
  '0.373',
  '40',
  '2021',
  '0.8'
)
Herkunft <- c(
  'Annahme',
  'Annahme',
  'Annahme',
  'Annahme',
  'Annahme',
  'Literatur',
  'Literatur',
  'Literatur',
  'Literatur',
  'Kalibration',
  'Annahme',
  'Literatur',
  'Literatur',
  'Literatur',
  'Literatur',
  'Literatur',
  'Literatur',
  'Kalibration',
  'Literatur',
  'Annahme'
)
tab_parameter <- cbind(Parameter,Bezeichnung,Einheit,Wert,Herkunft)
